### PR TITLE
Update doc of ConsumerSettings#withBlocker

### PR DESCRIPTION
**Pull request by bplommer**
See #582

### CODE REVIEW

**Comment by LMnet** [comment]
Do we really need to deprecate it? Maybe we could just add some additional information about requirements about thread-pool in the scaladoc. Because custom thread-pool may be useful for custom error handling, for logging, or to have good thread names.

**Comment by bplommer** [comment]
> Do we really need to deprecate it? Maybe we could just add some additional information about requirements about thread-pool in the scaladoc. Because custom thread-pool may be useful for custom error handling, for logging, or to have good thread names.

I don't have a particularly strong opinion on this. It does raise another question though - if this is an ability we want to keep, should we also allow users of 2.x to provide custom ExecutionContexts for blocking operations?

**Comment by LMnet** [comment]
> should we also allow users of 2.x to provide custom ExecutionContexts for blocking operations?

I think we should.

**Comment by bplommer** [comment]
> I think we should.

I'm fine with that. So we'd have `withCustomBlockingContext(ec: ExecutionContext)` in the `Settings` classes (I think the word `custom` should be there because it's confusing if `blockingContext` can be `None` when a blocking context is always required). The fact that we have a `Blocking` abstraction should make it pretty easy to do, as in #584.

**Comment by LMnet** [comment]
Sounds good for me.

**Comment by bplommer** [comment]
I've revised this PR to just update the doc - I'll go ahead and merge.

**Pull request merged**
