### PR TITLE
Use semaphore-like permits for some actor operations

### PR DESCRIPTION
**Pull request by bplommer**
This was supposed to be a demo but I got a bit carried away - inspired by #903

### CODE REVIEW

**Comment by bplommer** [comment]
Oops, I broke something somewhere along the line 😬

**Comment by LMnet** [comment]
I checked these changes briefly. They may be good by itself, but I talked about a different approach: I wanted to completely get rid of a `KafkaConsumerActor`. We don't need it actually. We could call а java consumer from the `fs2.kafka.KafkaConsumer` through semaphore without `KafkaConsumerActor`.

To create polling we could run a fiber that uses the same semaphore and the same java consumer and run this fiber in the background.

**Comment by vlovgr** [comment]
Ideally, we should process all fetch requests before polling, since partitions without fetch requests will remain paused when polling (as you note, we aren't really doing exactly that today). If it makes a difference in practice versus just processing everything FIFO is difficult to say. The only contract we really have to adhere to is to ensure poll is called at least every `max.poll.interval.ms`.

**Comment by bplommer** [comment]
Is there any objection to merging these changes as a step towards using a semaphore for everything?

**Review by LMnet — APPROVED** [review]

**Pull request merged**
