### PR TITLE
Add missing MkProducer argument, force compiler errors when they're missing

### PR DESCRIPTION
**Pull request by bplommer**
I'm not 100% happy with the added boilerplate, or with it being needed, but I don't have a better idea. Any thoughts?

### CODE REVIEW

**Comment by bplommer** [comment]
Exciting update: it doesn't compile with Scala 2.12 anyway. I guess I'll just leave the ambiguous implicits stuff out, but I'm still not happy with that.

**Comment by bplommer** [comment]
Exciting update no. 2: It now compiles in Scala 2.12, courtesy of added ugliness.

**Comment by LMnet** [comment]
Could you please explain why do we need this? As far as I understand, without `mkAmbig1` and `mkAmbig2` default instance of the `Mk???` instance will be used (which is derived from the `Sync`). And what is the problem with that?

**Comment by bplommer** [comment]
> Could you please explain why do we need this? 

It's not strictly needed, but it's an extra safeguard against us writing factory methods that don't require an `Mk` argument.

> As far as I understand, without `mkAmbig1` and `mkAmbig2` default instance of the `Mk???` instance will be used (which is derived from the `Sync`). And what is the problem with that?

There's no problem with the default instance derived from `Sync` being used, but that derivation needs to happen at the call site in user code so that the user can override the default behaviour if needed.

**Comment by LMnet** [comment]
Oh, so that's for library maintainers mostly, not for users. Ok, I got it.

**Review by LMnet — APPROVED** [review]

**Comment by bplommer** [comment]
This is intended to catch bugs like the one this PR fixes on lines 642-63 of `KafkaProducerConnection.scala`, where the `stream` method delegates to the `resource` method. Rather than `stream` taking a `MkProducer` argument it was autoderiving an instance based on `Sync`, which would prevent use of a custom instance by user code.

**Comment by bplommer** [comment]
> Oh, so that's for library maintainers mostly, not for users. Ok, I got it.

👍 didn't see your reply before my second comment

**Pull request merged**
