### PR TITLE
Added docs for graceful shutdown for cats-effect 3

### PR DESCRIPTION
**Pull request by LMnet**
Fix for #994

### CODE REVIEW

**Comment by bplommer** [comment]
This looks good but I want to look more closely before approving it.

Re mentioning multiple versions - if/when we migrate the docs to `sbt-typelevel-site` we can split that out into versioned documentation, which it supports via Laika.

**Comment by LMnet** [comment]
> if/when we migrate the docs to sbt-typelevel-site we can split that out into versioned documentation, which it supports via Laika.

It would be great!

**Comment by altrack** [comment]
I have tested this snippet with the series 3 and can confirm it doesn't lock.
CE is 3.4.9 FS2 is 3.6.1
Those are the version come with FS2-kafka 3.0.1
Got the following output after sending a SIGTERM to the running app:
```
Starting graceful shutdown
Finished stream
Succeeded in graceful shutdown
```

**Review by aartigao — APPROVED** [review]
Given that it was tested and works as expected, I'll be merging it because it's valuable information for the users and most of them are on CE 3.

**Pull request merged**
