### PR TITLE
Implement ScalaPB serialization

### LINKED ISSUE #634: Add ProtobufSettings for Registry
It would be nice if protobuf was supported in addition to Avro, something similar to https://github.com/fd4s/fs2-kafka/blob/series/2.x/modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala. If you're interested, I'd be willing to take a crack at this!

### PR DESCRIPTION
**Pull request by xela85**
Resolves #634 

I have added a new _ScalaPB_ module enabling the use of `KafkaProtobufDeserializer` and `KafkaProtobufSerializer` supporting Schema Registry. 

Its architecture is more or less copy pasted from Vulcan support. However there are two differences : 
- Protobuf serializer handles by itself "type safe" serialization by asking a type parameter. It calls itself Schema Registry. In order to avoid the use of Protobuf's `DynamicMessage`, it needs `specific.protobuf.value.type` containing the specified type to perform (de)serialization. 
- In order to support ScalaPB classes, we need a mapping between Scala and Java classes. Protobuf settings require themselves the Java one, but the (de)serializer uses the Scala one. Thanks to `JavaProtoSupport` inherited by `GeneratedMessageCompanion` when conversions are enabled, we can map these two types.

### CODE REVIEW

**Comment by bplommer** [comment]
Thanks for this! I haven’t had much time lately but I’ll try to take a look soon.

**Comment by bplommer** [comment]
I'm a bit nervous about making adding this to the main repo, as I don't have much knowledge/experience of protobuf and I don't think the other maintainers do either. Maybe you can release this as a separate library and we can add links to it from the readme and docs? Any thoughts on this @vlovgr @LMnet?

**Comment by vlovgr** [comment]
> Maybe you can release this as a separate library and we can add links to it from the readme and docs? 

This would be my preferred option as well, given my limited experience with protobuf and the fact we would have to maintain this going forwards if the changes are merged.

**Comment by xela85** [comment]
No problem, I will start a separate repo and contact you once the artifact published :). 
Besides, I have duplicated `SchemaRegistryClientSettings` and `Auth` in my ScalaPB module. 
These files could be moved out of the `vulcan` module (`core` ?) in order to use them elsewhere. 

Would this be a good idea for you ?

**Comment by bplommer** [comment]
> No problem, I will start a separate repo and contact you once the artifact published :). 

Great, let me know if there's anything I can help with!

> Besides, I have duplicated `SchemaRegistryClientSettings` and `Auth` in my ScalaPB module. 
> 
> These files could be moved out of the `vulcan` module (`core` ?) in order to use them elsewhere. 
> 
> 
> 
> Would this be a good idea for you ? 

I think we should consider doing this for the next major version (maybe in a `schema-registry` module), but there are some things about the design I'd like to revisit so let's copy-paste for now.

**Comment by rfan-debug** [comment]
@xela85 Is the protobuf support still under development?

**Comment by xela85** [comment]
It has been implemented as a separate project in https://github.com/fpe-cn/fs2-kafka-scalapb. 
However I dealt with issues with maven central publication (setup everything for my organisation is quite complicated). 
I will maybe try to publish that by myself later.

**Pull request closed without merging**
