### PR TITLE
Additional consumer functionality exposed

### PR DESCRIPTION
**Pull request by dmedser**
New methods added to `trait KafkaOffsets[F[_]]`:

```
def committed(partitions: Set[TopicPartition]): F[Map[TopicPartition, OffsetAndMetadata]]

def committed(partitions: Set[TopicPartition], timeout: FiniteDuration): F[Map[TopicPartition, OffsetAndMetadata]]
```

### CODE REVIEW

**Comment by dmedser** [comment]
@bplommer could you please give me a hint how to fix this CI error:

`* abstract method committed(scala.collection.immutable.Set)java.lang.Object in interface fs2.kafka.consumer.KafkaOffsets is present only in current version`?

**Comment by LMnet** [comment]
Hi @dmedser

Yes, you have to change MIMA rules to fix CI error.

**Comment by bplommer** [comment]
This is going to pass CI, but the change is genuinely going to break binary compatibility. So the options are either to retarget this PR at `Series/3.x` or add a new trait (`KafkaOffsetsV2`?) that extends `KafkaOffsets`.

**Comment by dmedser** [comment]
> This is going to pass CI, but the change is genuinely going to break binary compatibility. So the options are either to retarget this PR at `Series/3.x` or add a new trait (`KafkaOffsetsV2`?) that extends `KafkaOffsets`.

@bplommer Does this mean that whenever someone want to add some additional functionality, they will have to add a new trait with name KafkaXVN where X is Offsets and N is 2 as in my case?

Also if we consider this case with additional trait, what should `KafkaConsumer` look like? I suppose something like this:

```
sealed abstract class KafkaConsumer[F[_], K, V]
  extends KafkaConsume[F, K, V]
    with . . .
    with KafkaOffsetsV2[F]
    with . . .
``` 
where `KafkaOffsetsV2` extends `KafkaOffsets`, right?

**Comment by LMnet** [comment]
> change is genuinely going to break binary compatibility

Are you sure? As far as I know, adding new methods will not violate binary compatibility.

**Comment by bplommer** [comment]
> Are you sure? As far as I know, adding new methods will not violate binary compatibility.

Yes, because it's an unsealed trait. A mock `KafkaOffsets` implementation compiled against a previous version won't have implementations, but a user of that mock compiled against the new version will expect them, leading to a possible `NoSuchMethodException`.

**Comment by bplommer** [comment]
> @bplommer Does this mean that whenever someone wants to add some additional functionality, they will have to add a new trait with name KafkaXVN where X is Offsets and N is 2 as in my case?
> 
> Also if we consider this case with additional trait, what should `KafkaConsumer` look like? I suppose something like this:
> 
> ```
> sealed abstract class KafkaConsumer[F[_], K, V]
>   extends KafkaConsume[F, K, V]
>     with . . .
>     with KafkaOffsetsV2[F]
>     with . . .
> ```
> 
> where `KafkaOffsetsV2` extends `KafkaOffsets`, right?

Yes, that's all correct.

**Comment by dmedser** [comment]
@bplommer Is everything correct this time?

**Comment by dmedser** [comment]
@bplommer @LMnet could you guys trigger pipeline again please?

**Review by bplommer — APPROVED** [review]
LGTM

**Pull request merged**
